# Modelos e Estratégias de Trading
## Ajustando um modelo VAR à PETR4

Uirá Caiado. 05 de Setembro, 2016

**Resumo**

*Uma das principais necessidades quando falamos trading é realizar algum tipo de previsão sobre o estado futuro do instrumento operado para que possamos posicionar nossas ofertas. Como um dos objetivos da análise de séries temporais multivariadas é a realização de forecasts, nesta atividade vou implementar um modelo desta classe chamado Vetor Autoregressivo (VAR). Vou ajustar o modelo aos retornos e informações de book da PETR4 e analisar a performance realizando um back-test em uma parte dos dados coletados que ainda não tenha sido utilizada.*

## 1. Introdução

Nesta sessão vou ...


### 1.1. Modelagem ...

bla bla

In [2]:
import pandas as pd
df = pd.read_excel('data/VAR3_inputs_e_outputs.xlsx', header=None)

In [3]:
from statsmodels.tsa.api import VAR

In [13]:
l_index = pd.date_range(start= '01/01/2014', end='01/12/2016')
df.index = l_index[:df.shape[0]]
model = VAR(df)

In [28]:
results = model.fit(3)
pd.DataFrame(results.coefs[2]).to_clipboard()

In [30]:
results.bic

-41.325571126826091

In [22]:
results.summary()

  Summary of Regression Results   
Model:                         VAR
Method:                        OLS
Date:           Fri, 09, Sep, 2016
Time:                     21:44:21
--------------------------------------------------------------------
No. of Equations:         5.00000    BIC:                   -41.3256
Nobs:                     197.000    HQIC:                  -42.1191
Log likelihood:           2884.24    FPE:                2.98040e-19
AIC:                     -42.6589    Det(Omega_mle):     2.01701e-19
--------------------------------------------------------------------
Results for equation 0
           coefficient       std. error           t-stat            prob
------------------------------------------------------------------------
const         0.000005         0.001023            0.005           0.996
L1.0         -0.043374         0.079685           -0.544           0.587
L1.1          0.128951         0.077649            1.661           0.099
L1.2         -0.127479 

In [12]:
df.shape

(200, 5)

In [31]:
import statsmodels.tsa.vector_ar.util as util

In [137]:
aux = util.get_var_endog(df.values, 3)

In [138]:
import numpy as np
i_p = 3
na_y = df.values
na_one = np.array([1.])
l_Z = []
for i in xrange(i_p-1, len(na_y)-1):
    l_idx = range(i, i - i_p, -1)
    na_Zt = np.hstack([na_one, na_y[l_idx].ravel()])
    l_Z.append(na_Zt.T.copy())
na_Z = np.array(l_Z)

In [147]:
from numpy.linalg import inv

In [240]:
na_ysample = na_y[i_p:]  # Y := (y_1, ..., y_T)  (K x T) .T

In [226]:
params.shape

(16, 5)

In [222]:
na_ysample.shape

(197, 5)

In [165]:
inv(np.dot(na_Z, na_Z.T)).shape

(197, 197)

In [241]:
na_param = np.dot(na_ysample.T, np.dot(na_Z.T, inv(np.dot(na_Z, na_Z.T))).T).T

In [460]:
abs(results.coefs[0] - self.na_betahat[1:].reshape((3, 5, 5))[0]).sum()


3.9148372044106594e-15

In [422]:
self.na_A.swapaxes(1, 2).copy()[0]

array([[-0.04337403,  0.00532106,  0.00824174,  0.03580366, -0.06409133],
       [ 0.12895123,  0.17878003,  0.11517984,  0.1669593 , -0.05974308],
       [-0.1274789 ,  0.00375889, -0.05070792,  0.04865404, -0.09778579],
       [ 0.04964828,  0.03250922,  0.00721156, -0.11787292,  0.26814062],
       [-0.07125026, -0.07228295, -0.04194604, -0.04986425, -0.05419016]])

In [483]:
import var_model.vector_autoregression as var
reload(var)

<module 'var_model.vector_autoregression' from 'var_model/vector_autoregression.py'>

In [484]:
self = var.VectorAutoregression(df)

In [485]:
self.fit(3)

In [488]:
pd.DataFrame(self.na_A[0]).to_clipboard()

In [474]:
pd.DataFrame(self.na_betahat[1:].reshape(3, 5, 5)[0].T).to_clipboard()

In [400]:
self.na_A.swapaxes(1, 2)[0]

array([[-0.04337403,  0.12895123, -0.1274789 ,  0.04964828, -0.07125026],
       [ 0.00532106,  0.17878003,  0.00375889,  0.03250922, -0.07228295],
       [ 0.00824174,  0.11517984, -0.05070792,  0.00721156, -0.04194604],
       [ 0.03580366,  0.1669593 ,  0.04865404, -0.11787292, -0.04986425],
       [-0.06409133, -0.05974308, -0.09778579,  0.26814062, -0.05419016]])

In [393]:
results.params

0         1         2         3         4
const  0.000005  0.000422  0.000810 -0.000025 -0.001338
L1.0  -0.043374  0.005321  0.008242  0.035804 -0.064091
L1.1   0.128951  0.178780  0.115180  0.166959 -0.059743
L1.2  -0.127479  0.003759 -0.050708  0.048654 -0.097786
L1.3   0.049648  0.032509  0.007212 -0.117873  0.268141
L1.4  -0.071250 -0.072283 -0.041946 -0.049864 -0.054190
L2.0   0.013431 -0.244118 -0.047898 -0.043729 -0.028104
L2.1   0.001495 -0.004717  0.179970  0.159101  0.096378
L2.2  -0.242662 -0.345717 -0.487353 -0.365092 -0.391956
L2.3   0.245055  0.413840  0.295174  0.193884  0.162951
L2.4  -0.075217 -0.032270  0.055272  0.068610 -0.030571
L3.0  -0.044115 -0.075600 -0.110870 -0.040539 -0.046125
L3.1   0.015434 -0.076008  0.027031  0.032051 -0.081289
L3.2   0.056729  0.070572 -0.034428 -0.016870  0.247950
L3.3  -0.180469  0.017278 -0.013438 -0.037124 -0.131097
L3.4   0.065909  0.042417 -0.022812 -0.001811 -0.025088

In [398]:
pd.DataFrame(self.na_betahat - results.params.values)

0             1             2             3             4
0  -6.412039e-18  4.282599e-18  1.095044e-17  1.267500e-17 -1.431147e-17
1  -4.163336e-17  9.887924e-17  1.040834e-17  1.457168e-16  3.608225e-16
2   2.775558e-17 -1.110223e-16  3.330669e-16  1.110223e-16  4.163336e-17
3   0.000000e+00  1.452831e-16  2.359224e-16  6.938894e-18  3.885781e-16
4   1.595946e-16  1.249001e-16 -3.920475e-16 -1.249001e-16 -5.551115e-16
5  -8.326673e-17 -1.526557e-16 -2.012279e-16  1.387779e-17  4.857226e-17
6   3.469447e-17 -1.387779e-16  2.289835e-16 -1.457168e-16  4.857226e-17
7  -6.808790e-17 -8.326673e-17 -4.163336e-16 -1.942890e-16 -3.469447e-16
8   2.220446e-16 -1.665335e-16  7.771561e-16 -2.220446e-16  3.330669e-16
9  -8.326673e-17  2.220446e-16 -5.551115e-16  2.220446e-16  5.551115e-17
10  5.551115e-17  2.081668e-17 -4.857226e-17 -9.714451e-17 -2.081668e-16
11  1.110223e-16  6.938894e-17 -6.938894e-17 -2.706169e-16 -5.551115e-17
12  1.873501e-16 -6.938894e-17  2.289835e-16  1.318390e-16  2.775558e-17
13  2.498002e-16 -4.163336e-17  3.330669e-16  2.636780e-16 -2.775558e-16
14 -3.885781e-16  1.144917e-16 -1.769418e-16 -5.551115e-17  2.220446e-16
15 -8.326673e-17 -2.775558e-17  2.081668e-17  2.775558e-17 -1.006140e-16

In [284]:
        self.i_p = i_p  # VAR order
        self.na_A = None  # parameters estimator
        self.na_v = None  # intercep estimator
        i_K = self.df_Y.shape[1]  # number of variables
        self.already_fitted = True

In [285]:
        # reshape matrices
        self.na_Z = self._get_z_mat(i_p)  # Z := [Z_0, ..., Z_T] (T x Kp)
        na_Z = self.na_Z.T
        na_ysample = na_y[i_p:].T  # Y := (y_1, ..., y_T)  (K x T)

In [286]:
        # measure betas (Lutkepohl, p. 72):
        #    \hat{B} := YZ'(ZZ')^{-1}
        # where B.T:= (v, A_1, A_2, ..., A_p).T  ((Kp+1) x K)
        na_ZZTransp_inv = inv(np.dot(na_Z, na_Z.T))
        na_betahat = np.dot(np.dot(na_ysample, na_Z.T), na_ZZTransp_inv).T

In [290]:
a1, a2, a3 = na_betahat[1:].reshape((i_p, 5, 5))

In [316]:
na_u = na_ysample.T - np.dot(na_betahat.T, na_Z).T

In [318]:
np.dot(na_u.T, na_u)

array([[ 0.03533065,  0.01237248,  0.01004906,  0.01389852,  0.01162417],
       [ 0.01237248,  0.05127419,  0.02793373,  0.03007324,  0.02110267],
       [ 0.01004906,  0.02793373,  0.05596226,  0.04622673,  0.02275593],
       [ 0.01389852,  0.03007324,  0.04622673,  0.04839529,  0.02357024],
       [ 0.01162417,  0.02110267,  0.02275593,  0.02357024,  0.08344595]])

In [307]:
na_u.shape

(197, 5)

array([[ -1.92394646e-03,   4.24936041e-04,  -1.17908343e-02,
          2.93511293e-03,  -2.74535110e-02],
       [  5.15455921e-03,   8.66898828e-03,   1.13902795e-03,
          8.31319743e-03,  -3.83528636e-03],
       [  4.47527268e-03,   6.08023169e-04,   1.06244004e-02,
          5.67337096e-03,  -1.24490116e-02],
       [ -3.72381986e-03,  -1.65736715e-02,  -1.36726993e-02,
         -1.93832090e-02,   4.23513303e-03],
       [  7.72475215e-04,  -2.26483302e-03,  -4.11062382e-03,
          2.67277011e-03,  -5.99028390e-03],
       [  7.77400324e-03,   3.85028669e-02,   2.27233968e-02,
          2.11179575e-02,   3.06258483e-03],
       [  5.30668488e-03,  -2.04219621e-02,  -2.03758807e-02,
         -2.09014027e-02,  -9.93960990e-03],
       [  2.19941214e-02,   8.50514565e-03,   3.42448316e-03,
          2.07997040e-03,  -5.61360038e-04],
       [  1.44024473e-02,   1.53770231e-03,   6.07529261e-03,
          1.46646410e-02,   7.84622970e-03],
       [  3.39599261e-03,  -1.6024677

In [259]:
np.dot(na_ysample, np.dot(na_Z, inv(np.dot(na_Z.T, na_Z))))

array([[  5.46662839e-06,  -4.33740266e-02,   1.28951234e-01,
         -1.27478901e-01,   4.96482766e-02,  -7.12502594e-02,
          1.34311197e-02,   1.49463869e-03,  -2.42661604e-01,
          2.45055285e-01,  -7.52170124e-02,  -4.41147861e-02,
          1.54343780e-02,   5.67292783e-02,  -1.80469326e-01,
          6.59094286e-02],
       [  4.21955736e-04,   5.32105776e-03,   1.78780028e-01,
          3.75889103e-03,   3.25092218e-02,  -7.22829526e-02,
         -2.44117705e-01,  -4.71691222e-03,  -3.45717116e-01,
          4.13840014e-01,  -3.22701362e-02,  -7.55997832e-02,
         -7.60075652e-02,   7.05723131e-02,   1.72778880e-02,
          4.24166576e-02],
       [  8.10272981e-04,   8.24173822e-03,   1.15179836e-01,
         -5.07079197e-02,   7.21155964e-03,  -4.19460385e-02,
         -4.78979392e-02,   1.79970101e-01,  -4.87353425e-01,
          2.95173965e-01,   5.52724866e-02,  -1.10870219e-01,
          2.70305536e-02,  -3.44276725e-02,  -1.34382476e-02,
         -2.2811

In [208]:
na_ysample.shape

(197, 5)

In [209]:
params.shape

(16, 5)

In [185]:
params = np.linalg.lstsq(na_Z, na_ysample)[0]

In [186]:
params.shape

(16, 5)

In [189]:
results.coefs.shape

(3, 5, 5)

In [190]:
results.k_trend

1

In [201]:
pd.DataFrame(na_param)

0          1          2         3          4
0   -0.722156   0.103972  -0.991854 -1.470872  -1.399945
1   -2.172182   0.786844   1.061439  0.295728   3.125313
2    1.077401  -0.969465  -0.879180 -0.037860  -4.175208
3    1.556449  -1.635524  -3.692466 -2.555332   1.011859
4   -0.873046   4.590372   5.075378  4.680845   0.202479
5   -2.699137   2.409270   3.497993  1.736310   4.006859
6    3.659944  -4.536499  -5.340042 -2.885927  -6.120154
7   -1.812533   1.957782   1.678055  1.154255   1.518523
8   -2.777978   2.398514   0.760018 -0.258660   4.811770
9    7.415184  -4.860777  -4.654223 -1.360685 -12.748968
10  -0.063433   1.614033   2.099577  2.115171  -0.636052
11  -5.905873   6.380186   4.700603  2.268091  16.455421
12  -5.757457   4.549885   5.363690  2.104035  11.589851
13 -11.324143  14.746469   9.160361  5.883595  24.674465
14  11.629807 -16.896641 -11.288682 -7.378947 -25.897193
15   3.674572  -3.161057  -3.453601 -1.754360  -7.177701

In [197]:
params

array([[  5.46662839e-06,   4.21955736e-04,   8.10272981e-04,
         -2.47458751e-05,  -1.33776675e-03],
       [ -4.33740266e-02,   5.32105776e-03,   8.24173822e-03,
          3.58036613e-02,  -6.40913254e-02],
       [  1.28951234e-01,   1.78780028e-01,   1.15179836e-01,
          1.66959303e-01,  -5.97430793e-02],
       [ -1.27478901e-01,   3.75889103e-03,  -5.07079197e-02,
          4.86540416e-02,  -9.77857895e-02],
       [  4.96482766e-02,   3.25092218e-02,   7.21155964e-03,
         -1.17872920e-01,   2.68140622e-01],
       [ -7.12502594e-02,  -7.22829526e-02,  -4.19460385e-02,
         -4.98642496e-02,  -5.41901553e-02],
       [  1.34311197e-02,  -2.44117705e-01,  -4.78979392e-02,
         -4.37294991e-02,  -2.81041672e-02],
       [  1.49463869e-03,  -4.71691222e-03,   1.79970101e-01,
          1.59101362e-01,   9.63784357e-02],
       [ -2.42661604e-01,  -3.45717116e-01,  -4.87353425e-01,
         -3.65091893e-01,  -3.91956456e-01],
       [  2.45055285e-01,   4.1384001

In [59]:
df.head()


0         1         2         3         4
2014-01-01  0.004082  0.007782  0.033859  0.023865  0.041760
2014-01-02  0.012377  0.019575  0.052446  0.056654 -0.010573
2014-01-03 -0.006921 -0.011853 -0.005707 -0.017716 -0.019980
2014-01-04  0.000579  0.005753 -0.020576 -0.004274 -0.036814
2014-01-05  0.001156  0.011407 -0.003350  0.003459  0.000000

## 2. Implementando o Modelo

Nesta sessão detalharemos e implementaremos ...

### 2.1. Bla

bla bla


## 4. Conclusão

bla bla




## 5. Últimas Considerações

bla bla


*Style notebook and change matplotlib defaults*

In [5]:
#loading style sheet
from IPython.core.display import HTML
HTML(open('ipython_style.css').read())

In [6]:
#changing matplotlib defaults
%matplotlib inline
import seaborn as sns
sns.set_palette("deep", desat=.6)
sns.set_context(rc={"figure.figsize": (8, 4)})
sns.set_style("whitegrid")
sns.set_palette(sns.color_palette("Set2", 10))